spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: domain-service
          uri: lb://domain-service
          predicates:
            - Path=/v1/saupay/**


#uri : lb://domain-service --> lb : load balancer .. yazmasaydık tek bir instance üzerinden çalışırdı.
#tüm istekleri domain-service'e yönlendirir
#V1/saupay/** altındaki tüm istekleri domain-service'e yönlendirir
#id: name
#uri:bağlanılacak servisin app name 'i        -
#predicates: hangi controller lar kullanılacak

  #zipkin:
   # base-url: http://localhost:9411

server:
  port: 8888

eureka:
    client:
        serviceUrl:
            registerWithEureka: true
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true


manangment:
  endpoints:
    web:
      exposure:
        include: "*"
#bu kod ile tüm endpointleri açtık.



