
version: '3.7'
services:

  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=paymentdb
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=guzelomerfaruk9@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"

